name: coaching_beton
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  get: ^4.7.2
  go_router: ^16.2.2
  google_fonts: ^6.3.1
  hive: ^2.2.3
<<<<<<< HEAD
  hive_flutter: ^1.1.0
  pinput: ^5.0.2
  smooth_page_indicator: ^1.2.1
=======
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.2
  riverpod: ^3.0.1
>>>>>>> 378ad7acaa007d3812f6d35a33301432cf78242a
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
